### ISSUE TITLE
Errors with tailwindcss 2.2.4

### ISSUE THREAD

**Issue by aleadag** [UltimateZero/gridsome-plugin-tailwindcss2#1]
When I installed tailwindcss@latest (2.2.4). It says:

`Error: Cannot find module 'tailwindcss/lib/cli/compile'`

If I reverted tailwindcss to 2.1.x, it works.

**Comment by AtHisBest** [comment]
Have the same issue, any chance to fix it?

Any workaround for now?

**Comment by mklueh** [comment]
I also have the same problem, even with 2.1.4.

Where does this module 'tailwindcss/lib/cli/compile' come from? 

Would really appreciate this plugin, as setting up tailwind with gridsome is really a mess, hard to grasp why things aren't working

**Comment by UltimateZero** [comment]
Sorry for the late response!

It seems that the structure of the files in the latest tailwind has changed and it no longer includes the compiler file.
I can dig in the new structure and see if there's an alternative, but I would really recommend using the other [gridsome tailwind plugin](https://github.com/brandonpittman/gridsome-plugin-tailwindcss).

If, for some reason, the other plugin is not working out for you and you need this one, let me know. :)

**Comment by AtHisBest** [comment]
Hey @UltimateZero Thanks for your reply

I remember when using the other plugin getting into errors, your plugin worked great, was a major help.

**Comment by BSBjorn** [comment]
Yeah, I have the same issue.

**Comment by bartomiak** [comment]
same issue here :(

**Comment by ffxsam** [comment]
BTW, the other plugin is marked as archived in GitHub. I'm not sure it's a great idea for anyone to use it.

**Comment by UltimateZero** [comment]
Hi everyone!

Sorry again for the unavailability. I will try my best to find time to maintain this repo since the other one is archived. (PRs are always welcome!).

**Comment by UltimateZero** [comment]
Issue fixed in 3.0.1

**Comment by AtHisBest** [comment]
Thanks, @UltimateZero for fixing it

By the way any chance to get an upgrade to v3?

**Comment by UltimateZero** [comment]
@AtHisBest Yes. It supports v3 now actually! :)

**Comment by AtHisBest** [comment]
That's awesome, you might want to update the read me it still says currently v2)  

And the title from gridsome-plugin-tailwindcss2 to gridsome-plugin-tailwindcss3

Thanks so so much
