### ISSUE TITLE
Apparently not working

### ISSUE THREAD

**Issue by guifelix** [UltimateZero/gridsome-plugin-tailwindcss2#2]
- Followed the instructions with `v3.0.1` and it did not work.
- Tried using previous versions as well (`v3.0.0` and `v1.0.3`) but they had some errors when initializing the plugin.

**Comment by UltimateZero** [comment]
@guifelix Hi, can you post the errors you're getting? 
I've just tried to create a fresh project with this plugin and it seems to be working fine.
